### ISSUE TITLE
pip installation on Google colab

### ISSUE THREAD

**Issue by kno10** [ThrunGroup/BanditPAM#160]
pip install on Google colab does not work.
```
!pip install banditpam
Collecting banditpam
  Using cached banditpam-1.0.2.tar.gz (195 kB)
WARNING: Discarding https://files.pythonhosted.org/packages/65/2f/e37b64df0af49afb507e5f9470665381909e00b78c88c73d1e380f83df8c/banditpam-1.0.2.tar.gz#sha256=4cb13dd99c05d3ab797224beba60cda46dee4d96c251ea0f1ad31491cc12339d (from https://pypi.org/simple/banditpam/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Using cached banditpam-1.0.0.tar.gz (194 kB)
WARNING: Discarding https://files.pythonhosted.org/packages/c5/9a/5c21e1ea5a8d1d034c437247e62b81183f10f8cb99c99802dcd097bdd063/banditpam-1.0.0.tar.gz#sha256=8dc3a3e7d2c53e73c5393b95c40a7b912f427dcc34d8b1c03634b7403d626f72 (from https://pypi.org/simple/banditpam/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement banditpam (from versions: 1.0.0, 1.0.2)
ERROR: No matching distribution found for banditpam
```

**Comment by motiwari** [comment]
Hi Prof. Schubert, thank you for filing a bug report! Could you try now with `!pip install --no-cache-dir banditpam` ? I've fixed the issue in `v1.0.5`; see below:

![image](https://user-images.githubusercontent.com/13426340/146850185-c5ec3553-a52c-47fd-a952-74dd3ec65d9d.png)

If the problem persists, please reopen this Github issue.

For posterity:
- Currently, the default Google Colab is on an Ubuntu 18.04 VM. That is the only type of VM that our `setup.py` currently supports on Google Colab
- On Google Colab, we need to install a number of dependencies via `apt`
- We then need to install `libarmadillo10`. Tragically, the only [prebuilt libraries](https://launchpad.net/ubuntu/+source/armadillo/) for `armadillo` go up to version 8. This is too old; we require `armadillo >= 10.5.3`. 
- To circumvent this, I installed a newer version of `cmake` on a Colab Runtime, used it to build `armadillo`, and then added the necessary libraries to this repository
- I then changed the `setup.py` to check if we're within a Google Colab Runtime, and if so, copy the necessary, pre-built `armadillo` libraries to the Google Colab Runtime.
- Note: the shipped libraries only work on `Ubuntu 18.04`. When the default Colab Runtime changes, we'll need to rebuild them. It's preferable to ship the pre-built libraries in this repo itself so that we don't force users to download and compile `cmake` all to build `armadillo`, which is a very time-consuming process.

**Comment by kno10** [comment]
It is unusual IMHO to have pip try to automatically install anything non-python. I haven't even seen one compile anything before, usually they appear to come with "private copies" of precompiled shared libraries. Neither of both is IMHO a good solution, but that is a general design issue of pip (and why it is considered a security risk).
Either way, for the purpose of testing banditpam on colab, this approach seems to work (for now).

**Comment by motiwari** [comment]
Very good points. In fact, we built the python wheels directly for users earlier (so no user-side compilation was necessary), but a dependency broke our build process (see here)[https://github.com/RUrlus/carma/issues/95], so right now we are shipping only the source. Once we repair it, we'll rebuild the wheels for users
